version: '3.8'

services:
  reaper-desktop:
    build:
      context: .
      dockerfile: base/Dockerfile
    image: ${DOCKERHUB_USERNAME:-schnicklbob}/quickpod-reaper-base:latest
    container_name: reaper-desktop
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "6901:6901"
      - "8686:8686"
    environment:
      - VNC_PW=${VNC_PASSWORD:-quickpod123}
      - DISPLAY=:1
      - VNC_PORT=6901
      - HEALTH_PORT=8686
      - ENABLE_RVC=0
      - ENABLE_MUSICGEN=0
      - ENABLE_UVR=0
    volumes:
      - ./workspace:/home/kasm-user/workspace
      - ./audio:/home/kasm-user/audio
      - ./reaper-config:/home/kasm-user/.config/REAPER
      - ./logs:/var/log/quickpod
    shm_size: "8gb"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8686 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 6
      start_period: 20s
