name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'base/**'
      - 'covers/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-base:
    name: Build Base Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-base-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-base-

      - name: Build and push base image
        id: docker_build_base
        uses: docker/build-push-action@v5
        with:
          context: ./base
          push: true
          tags: |
            schnicklbob/quickpod-reaper-base:latest
            schnicklbob/quickpod-reaper-base:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          platforms: linux/amd64

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Image digest
        run: echo "Base image pushed with tags latest and ${{ github.sha }}"

  build-covers:
    name: Build Covers Image
    needs: build-base
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.event.head_commit.modified, 'covers/')
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-covers
          key: ${{ runner.os }}-buildx-covers-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-covers-

      - name: Build and push covers image
        id: docker_build_covers
        uses: docker/build-push-action@v5
        with:
          context: ./covers
          push: true
          tags: |
            schnicklbob/quickpod-reaper-covers:latest
            schnicklbob/quickpod-reaper-covers:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache-covers
          cache-to: type=local,dest=/tmp/.buildx-cache-covers-new,mode=max
          platforms: linux/amd64
          build-args: |
            BASE_IMAGE=schnicklbob/quickpod-reaper-base:latest

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-covers
          mv /tmp/.buildx-cache-covers-new /tmp/.buildx-cache-covers

      - name: Image digest
        run: echo "Covers image pushed with tags latest and ${{ github.sha }}"
