name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'base/**'
      - 'covers/**'
      - 'opt/**'
      - 'usr/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-base:
    name: Build Base Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: base/Dockerfile
          push: true
          tags: |
            schnicklbob/quickpod-reaper-base:latest
            schnicklbob/quickpod-reaper-base:${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: echo Base image pushed with tags latest and ${{ github.sha }}

  build-covers:
    name: Build Covers Image
    needs: build-base
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push covers image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: covers/Dockerfile
          push: true
          tags: |
            schnicklbob/quickpod-reaper-covers:latest
            schnicklbob/quickpod-reaper-covers:${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BASE_IMAGE=schnicklbob/quickpod-reaper-base:latest
